name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name metaanalysisacr

      - name: Build and Push Docker Image
        run: |
          docker build -t metaanalysisacr.azurecr.io/backend:latest backend/
          docker push metaanalysisacr.azurecr.io/backend:latest

      - name: Restart Web App to Apply New Image
        run: |
          az webapp restart --name meta-analysis-backend --resource-group meta-analysis-resource-group

          