name: Frontend CI Pipeline
on:
  push:
    branches:
      - be3  # Deploy frontend when code is pushed to main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: |
          cd meta-analysis-app  # Adjust to match your frontend folder
          npm install
      - name: Build Frontend
        run: |
          cd meta-analysis-app
          npm run build
      - name: Deploy to Azure Web App (Frontend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: "meta-analysis"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: meta-analysis-app/dist  # This is the frontend build output folder
          